### ISSUE TITLE
Error when new user views register page with token

### ISSUE THREAD

**Issue by digitalight** [LaravelDaily/Laravel-Auth-Invitations#2]
Followed the guide and everything works up until the user tries to browse to the generated url with token and gets the following error:

Class App\Http\Controllers\Auth\Request does not exist

I guess somewhere in the new code it is looking for a Auth\Request controller but it doesn't exist. Checked on repo version too and no Auth\Request controller present in the demo code.
Am trying to run this on latest 5.8. Is it still compatible?

**Comment by PovilasKorop** [comment]
We didn't upgrade this repo since 5.5 and there are possibly some changes, but in your case I think it's referencing Request from Illuminate, so what you need to do is on the top add use Illuminate\Http\Request; - I think it's this syntax, not 100% sure as I'm off computer currently, so typing from the memory.

**Comment by digitalight** [comment]
Thank you so much that fixed my issue.
I added the following 2 lines to RegisterContoller.php
`use Illuminate\Http\Request;`
`use App\Invitation;`
